### ISSUE TITLE
The descriptions of creeper explosion damaging environment and entities are swapped in forge config

### ISSUE THREAD

**Issue by Nurdoidz** [DragonsPlusMinecraft/CreeperFirework#10]
When configuring the mod on Forge, if the player only looks at the comments and not the actual keys, they may set the wrong settings. Very minor issue. Mods like [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) will parse comments as tooltips:

![image](https://github.com/DragonsPlusMinecraft/CreeperFirework/assets/8064810/b3cf06e4-d2c1-4004-a4d4-9a849782c97d)

`plus.dragons.creeperfirework.forge.misc.ConfigurationForge` class, lines 24–27:

```java
        CREEPER_FIREWORK_HURT_CREATURE = builder.comment("Will the active-explosion firework destroy nearby environment just like creeper normally exploding?")
                .define("CREEPER_FIREWORK_HURT_CREATURE", false);
        CREEPER_FIREWORK_DESTROY_BLOCK = builder.comment("Will the active-explosion firework effect hurt nearby creature?")
                .define("CREEPER_FIREWORK_DESTROY_BLOCK", false);
```

**Comment by MarbleGateKeeper** [comment]
Thanks
