### ISSUE TITLE
Building for 1.19.3

### ISSUE THREAD

**Issue by beowuff** [DragonsPlusMinecraft/CreeperFirework#3]
I'm currently getting:

C:\Users\beowu\git\CreeperFirework\src\main\java\love\marblegate\creeperfirework\mixin\MixinCreeperEntity.java:110: error: incompatible types: CreeperEntity cannot be converted to Explosion
victim.damage(DamageSource.explosion((CreeperEntity) (Object) this), (float) ((int) ((v * v + v) / 2.0D * 7.0D * (double) j + 1.0D)));

I'm trying to figure out if it's me or my setup... I'm not super familiar with java.

**Comment by MarbleGateKeeper** [comment]
Thx buddy. It's due to Minecraft Changed some codes. I fixed it and I'll upload a new version now.

--------------
File on cf is still in processing, you can download here: https://modrinth.com/mod/creeper-firework/version/1.5.0
