### ISSUE TITLE
Can you set it as fireworks？

### ISSUE THREAD

**Issue by QianMuu** [DragonsPlusMinecraft/CreeperFirework#5]
If your fireworks special effects could turn into rocket fireworks, I think it would be very beautiful.

**Comment by MarbleGateKeeper** [comment]
Can you explain your idea more specifically?

**Comment by QianMuu** [comment]
> 

I am looking for fireworks modules, but they are rare.
Similar to: https://www.curseforge.com/minecraft/mc-mods/phireworks
So, if you're interested, I'm lucky to be able to experience your fireworks module.

**Comment by MarbleGateKeeper** [comment]
Sorry, I don't have time to do it now.
