### ISSUE TITLE
Mistranslation in Simplified Chinese

### ISSUE THREAD

**Issue by ghost** [DragonsPlusMinecraft/CreeperFirework#9]
**Describe the bug**
Using Chinese (Simplified) then open the Creeper Firework Setting, 
the option "CREEFER DEATH FIREWORK HURTS CREATURE" was mistranslated.

**To Reproduce**
1. Start the game.
2. Change language to Simplified Chinese.
3. Open the mod menu and enter the settings.
4. Found the incorrect translation.

**System Information**

- Minecraft 1.20.1, Fabric 0.15.6
- Installed Mods: modmenu-7.2.2, creepre_firework-2.1.0, cloth-config-11.1.118-fabric, fabric-api-0.91.0+1.20.1.
- OS: Windows 11

**Comment by MarbleGateKeeper** [comment]
Fixed. Thanks for report!
